name: Trigger auto deployment for dan

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/dan-AutoDeployTrigger-ef738f56-32bc-4c31-a282-3b25c2f2b6b4.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DAN_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: contoso34.azurecr.io
          registryUsername: ${{ secrets.DAN_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DAN_REGISTRY_PASSWORD }}
          containerAppName: dan
          resourceGroup: 1234danleo
          imageToBuild: contoso34.azurecr.io/dan:${{ github.sha }}
          
            

     

